---
- name: Установка и настройка Alfresco Community
  hosts: virtual
#   become: yes

  roles:
    # - { role: server_preparation_and_install_alfresco, when: ansible_distribution == "Ubuntu", become: yes }
    - { role: installing_a_business_platform, when: ansible_distribution == "Ubuntu", become: yes }
